#!/usr/bin/env bash

# This script is idempotent.

set -euxo pipefail

CHAIN=$1
DOMAIN=$2
BRANCH=$3
COMMIT=$4
REVISION="ord-$BRANCH-$COMMIT"

case $CHAIN in
  main)
    CSP_ORIGIN=ordinals.com
    ;;
  regtest)
    CSP_ORIGIN=regtest.ordinals.com
    ;;
  signet)
    CSP_ORIGIN=signet.ordinals.com
    ;;
  test)
    CSP_ORIGIN=testnet.ordinals.com
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

touch ~/.hushlogin

sed -i -E 's/#?PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

mkdir -p \
  /etc/systemd/system/litecoind.service.d \
  /etc/systemd/system/ord.service.d

printf "[Service]\nEnvironment=CHAIN=%s\nEnvironment=CSP_ORIGIN=%s\n" $CHAIN $CSP_ORIGIN \
  | tee /etc/systemd/system/litecoind.service.d/override.conf \
  > /etc/systemd/system/ord.service.d/override.conf

hostnamectl set-hostname $DOMAIN

apt-get install --yes \
  acl \
  clang \
  curl \
  libsqlite3-dev\
  libssl-dev \
  locales-all \
  pkg-config \
  ufw \
  vim

ufw default allow outgoing
ufw default deny incoming

ufw allow 8080
ufw allow http
ufw allow https
ufw allow ssh

case $CHAIN in
  main)
    ufw allow 9333
    ;;
  regtest)
    ufw allow 18444
    ;;
  signet)
    ufw allow 39333
    ;;
  test)
    ufw allow 19333
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

ufw --force enable

if ! which litecoind; then
  ./bin/install-litecoin-core-linux
fi

litecoind --version

if [[ ! -e ~/.cargo/env ]]; then
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
fi

source ~/.cargo/env

rustup update stable

cargo build --release
install --backup target/release/ord /usr/local/bin/ord

id --user litecoin || useradd --system litecoin
id --user ord || useradd --system ord

cp deploy/litecoind.service /etc/systemd/system/

mkdir -p /etc/litecoin
cp deploy/litecoin.conf /etc/litecoin/litecoin.conf

if [[ ! -e ~/.litecoin/litecoin.conf ]]; then
  mkdir -p ~/.litecoin
  ln -s /etc/litecoin/litecoin.conf ~/.litecoin/litecoin.conf
fi

systemctl daemon-reload
systemctl enable litecoind
systemctl restart litecoind

case $CHAIN in
  main)
    COOKIE_FILE_DIR=/var/lib/litecoind
    ;;
  regtest)
    COOKIE_FILE_DIR=/var/lib/litecoind/regtest
    ;;
  signet)
    COOKIE_FILE_DIR=/var/lib/litecoind/signet
    ;;
  test)
    COOKIE_FILE_DIR=/var/lib/litecoind/testnet3
    ;;
  *)
    echo "Unknown chain: $CHAIN"
    exit 1
    ;;
esac

while [[ ! -f $COOKIE_FILE_DIR/.cookie ]]; do
  echo "Waiting for litecoind…"
  sleep 1
done

setfacl -m ord:x /var/lib/litecoind
setfacl -m ord:x $COOKIE_FILE_DIR
setfacl -dm ord:r $COOKIE_FILE_DIR
setfacl -m ord:r $COOKIE_FILE_DIR/.cookie

journalctl --unit ord --vacuum-time 1s

cp deploy/ord.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable ord
systemctl restart ord

while ! curl --fail https://$DOMAIN/status > /dev/null; do
  echo "Waiting for ord at https://$DOMAIN/status…"
  sleep 1
done
